[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"  # Use the Netlify Next.js plugin to support SSR and dynamic routes

[context.production.environment]
  node_version = "18.17.0"
