import { FC } from "react";
import { SectionWrapper } from "../Common/SectionWrapper";
import {
  ParagraphContainer,
  SectionContainer,
  SectionParagraph,
  SubTitle,
  ServiceItem
} from "../Common/Common-styles";
import { Box, useTheme } from "@mui/material";
import { QortalSVG } from "../../../Common/Icons/QortalSVG";

interface SectionProps {
  title: string;
  setSelectedSection: (sectionId: string) => void;
  id: string;
}
export const ServiceTypes: FC<SectionProps> = ({
  title,
  setSelectedSection,
  id
}) => {
  const theme = useTheme();

  return (
    <SectionWrapper
      title={title}
      setSelectedSection={setSelectedSection}
      id={id}
    >
      <SectionContainer>
        <ParagraphContainer>
          <SubTitle>Public services</SubTitle>
          <SectionParagraph>
            The services below are intended to be used for publicly accessible
            data.
          </SectionParagraph>
          <Box sx={{ margin: "20px 0" }}>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              IMAGE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              THUMBNAIL
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              VIDEO
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              AUDIO
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              PODCAST
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              VOICE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              ARBITRARY_DATA
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              JSON
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              DOCUMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              LIST
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              PLAYLIST
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              METADATA
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              BLOG
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              BLOG_POST
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              BLOG_COMMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              GIF_REPOSITORY
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              ATTACHMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              FILE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              FILES
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              CHAIN_DATA
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              STORE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              PRODUCT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              OFFER
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              COUPON
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              CODE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              PLUGIN
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              EXTENSION
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              GAME
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              ITEM
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              NFT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              DATABASE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              SNAPSHOT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              COMMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              CHAIN_COMMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              WEBSITE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              APP
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              QCHAT_ATTACHMENT
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              QCHAT_IMAGE
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              QCHAT_AUDIO
            </ServiceItem>
            <ServiceItem>
              <QortalSVG
                color={theme.palette.text.primary}
                height={"18"}
                width={"18"}
              />
              QCHAT_VOICE
            </ServiceItem>
          </Box>
          <SubTitle>Private services</SubTitle>
          <SectionParagraph>
            For the services below, data is encrypted for a single recipient,
            and can only be decrypted using the private key of the recipient's
            wallet.
          </SectionParagraph>
          <SectionParagraph>
            QCHAT_ATTACHMENT_PRIVATE, ATTACHMENT_PRIVATE, FILE_PRIVATE,
            IMAGE_PRIVATE, VIDEO_PRIVATE, AUDIO_PRIVATE, VOICE_PRIVATE,
            DOCUMENT_PRIVATE, MAIL_PRIVATE, MESSAGE_PRIVATE
          </SectionParagraph>
        </ParagraphContainer>
      </SectionContainer>
    </SectionWrapper>
  );
};
